meta_title: "RemplaMatch - Le remplacement médical en toute simplicité"
meta_description: "Description générique."
meta_image: "image.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@nomdevotrecompte" # indispensable pour les Twitter Cards
